server:
  port: 8084

spring:
  application:
    name: auth
  datasource:
    url: jdbc:postgresql://postgres:5432/auth
    username: amigoscode
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  zipkin:
    base-url: http://zipkin:9411

jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  expiration: 86400000  # 1 day in milliseconds
  refresh-token:
    expiration: 1800000  # 30 minutes in milliseconds

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true